version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: slackdump-db
    environment:
      POSTGRES_USER: slack
      POSTGRES_PASSWORD: slack
      POSTGRES_DB: slackdump
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slack -d slackdump"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: slackdump-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      # --- Slack ---
      SLACK_TOKEN: "xoxb-your-token-here"
      # Optional to restrict default listed types
      SLACK_TYPES: "public_channel,private_channel"
      FETCH_THREADS: "true"
      FETCH_FILES: "false"

      # --- DB ---
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: slack
      DB_PASSWORD: slack
      DB_NAME: slackdump

      # --- Limits / Ranges (optional) ---
      OLDEST_TS: "0"
      LATEST_TS: ""

    ports:
      - "8080:8000"
    command: ["python", "-u", "/app/app.py"]
    restart: "unless-stopped"

volumes:
  pgdata:
